// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spdnawxonpvwdjmuolat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwZG5hd3hvbnB2d2RqbXVvbGF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODg1NjMsImV4cCI6MjA2MTE2NDU2M30.ItlBKlwOWKyENRvLRmyRdOA0y3p4QeBCouv_rAE7tqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});